apiVersion: v1
kind: Secret
metadata:
  name: api-producao-secret
type: Opaque
data:
  connectionString: SG9zdD10ZWNoY2hhbGxlbmdlcHJvZHVjYW8uY3A0Y3VmYTAwd2E5LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtQb3J0PTU0MzI7RGF0YWJhc2U9dGVjaGNoYWxsZW5nZXByb2R1Y2FvO1VzZXJuYW1lPXBvc3RncmVzcHJvZHVjYW87UGFzc3dvcmQ9cG9zdGdyZXNwcm9kdWNhbztJbmNsdWRlIEVycm9yIERldGFpbD10cnVl