apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pedido-deployment
  labels:
    app: api-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pedido
  template:
    metadata:
      name: pod-api
      labels:
        app: api-pedido
    spec:
      containers:
        - name: api-pedido-container
          image: andssil/techchallenge-pedido:latest
          ports:
            - containerPort: 8080
          env:  
            - name: ASPNETCORE_ENVIRONMENT
              value: Production                         
            - name: ConnectionStrings__Database
              valueFrom: 
               secretKeyRef:
                name: api-pedido-secret
                key: connectionString
          imagePullPolicy: IfNotPresent               
          resources:
            requests:
              cpu: 50m  