apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  connectionString: SG9zdD10ZWNoY2hhbGxlbmdlLmN2eHNneG5lb2Rmby51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb207UG9ydD01NDMyO0RhdGFiYXNlPXRlY2hjaGFsbGVuZ2U7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM7SW5jbHVkZSBFcnJvciBEZXRhaWw9dHJ1ZQ==